openSUSE/osc

osc/cmdln.py
This was already fixed in the original module:
https://github.com/trentm/cmdln/issues/1
While this might not impact out-of-the-box `osc` client, it is useful if a plugin wants to provide an interactive interface, which is how I stumbled over it.
=> Fix readline support in cmdln-module

osc/build.py
Little Endian host can do build in Big Endian VM
Signed-off-by: Dinar Valeev <dvaleev@suse.com>
=> ppc64le can build ppc64 in KVM

dist/complete.sh, dist/osc.complete
https://bugzilla.opensuse.org/show_bug.cgi?id=915037
Tested that it can complete commands and project+subproject names
=> Fix completion for scp

osc/util/packagequery.py
=> Support native Debian packages in pkg-prefer

osc/commandline.py, osc/core.py
useful to workaround https://github.com/openSUSE/open-build-service/issues/913
=> allow force commit

osc/core.py, tests/common.py, tests/test_commit.py
This change fixes errors when running test suite with Python 3.
=> Fix Python 3 support.

osc/core.py
TypeError: can only concatenate list (not "tuple") to list
=> fix exception

osc/commandline.py
=> Added missing localrun help text to do_service

osc/build.py, osc/conf.py
this needs https://github.com/openSUSE/obs-build/pull/245 to work
=> add vm-user option

osc/commandline.py
FIX openSUSE/open-build-service#1591
=> FIX https://github.com/openSUSE/open-build-service/issues/1591

osc/commandline.py, osc/core.py
Since the API controller functions are now fixed and support this, add revision control options to the osc meta calls
`osc meta prj|prjconf -r|--revision REV`
to checkout any revision and
`osc meta prj|prjconf [-m|--message TEXT] [-e] [-F file]`
to add an optional commit message.
It is compatible to older API releases.
Tested with 0.154.0 because of the broken master.
=> Add revision control options to meta project commands

osc/commandline.py
to make it easier to find with
man osc | grep key
=> mention "key" in no-verify help text

osc/babysitter.py
As I haven't found any good source for choice of exit code, I took value
130 found here:
http://tldp.org/LDP/abs/html/exitcodes.html
=> Return different return code on KeyboardInterrupt

dist/osc.complete
Signed-off-by: Olaf Hering <olaf@aepfle.de>
=> Check for existance of .oscrc before collecting alias

dist/osc.complete, osc/commandline.py
Just a simple spelling fix.  Issue #220
=> Fix spelling of --separate-requests

osc/commandline.py
Uses the new --wipe option of build to delete build-roots.
=> Add 'wipe' subcommand to delete buildroots

osc/conf.py
This change makes basic authentication fail after first unsuccessful
attempt (instead of automatically retrying) and thus prevents unnecessary
failed login attempts.
The problem can at least be reproduced on Ubuntu 14.04 with Python 2.7.6.
This change also allows printing the contents of an HTTP 401 message to
the user.
=> Backport a fix from Python 2.7 upstream for urllib2.

osc/core.py
Closes https://github.com/openSUSE/osc/issues/264.
=> Lex the contents of $PAGER to support pager commands with arguments.

dist/osc.complete, osc/commandline.py, osc/core.py
added comments subcommand to osc: 
```
osc comment list package PROJECT PACKAGE
osc comment list project PROJECT 
osc comment list request ID
```
```
osc comment create package PROJECT PACKAGE 'COMMENT' [-p parent_id]
osc comment create project PROJECT 'COMMENT' [-p parent_id]
osc comment create request ID 'COMMENT' [-p parent_id]
```
``` 
osc delete comment ID
```
This PR needs this to be merged before it works: https://github.com/openSUSE/open-build-service/pull/2722
This is for issue #250
=> integrated comments command

osc/core.py
multibuild compatibility mode for old apis
=> multibuild compatibility mode for old apis

osc/core.py
fixes #175 
The user must enter a valid option to proceed.
=> fixes issue #175 / invalid input at prompt

osc/commandline.py, osc/core.py
new switch (--issues-only) which will only show the issues that differ.
=> added switch to show only issues in rdiff

osc/cmdln.py
to enable reproducible builds of osc packages
=> Allow to override man-page date

osc/commandline.py
Useful e.g. for factory-maintainers
=> Allow requesting maintainership for group and project

osc/commandline.py
fixes #288 
proc is now mounted (similar to build script). 
If the mount fails an error is displayed, but you get chrooted nevertheless.
=> fixed chroot to use proc

osc/build.py
Relevant changes on obs-build here:
https://github.com/openSUSE/obs-build/pull/372/files#diff-b3d786e8f98e373cc94080b87619df38R110
=> Set build files for fissile

osc/commandline.py
=> added -M switch to osc triggerreason

osc/commandline.py
This will filter the requests you get to review based on
the tgt_package in the action element.
This helps reviewers who want just to review a subset of requests or
do **not** want to review some packages.
Examples:
```
```
@marcus-h: Can you review please ;) It would be better to get the filtered packages returned by the api. But AFAIK the api does not support regular expressions at this point. So this is the fastest thing I could come up with. 
As always: Feedback very welcome.
=> add --package-filter option to osc review list

osc/commandline.py, osc/core.py
show and edit group meta: 
```
osc meta group <mygroup>
osc meta group -e <mygroup>
```
=> add meta group function to edit / show group meta

osc/commandline.py, osc/core.py
renamed get_group to get_group_meta.  
@marcus-h: please review.
=> renamed get_group to get_group_meta.

osc/core.py
show comments for the request in interactive mode.
=> show user comments in interactive mode

osc/build.py
This adds a hint for package suffix using the BinaryType from the build config
This fixes #321.
=> Add pacsuffix hint using BinaryType from build config

osc/core.py
Show rpmlintlog in interactive mode.
Gives the user a list with possible repo/arch combinations he can choose from.
=> show lintlog (li) in interactive mode

osc/core.py
To get a better overview in the interactive review mode the issues connected to 
the submitrequest are shown. 
Additionally to the bugnumber the following information will be shown: 
- Summary
- Status
The output looks like this
`## BUG# boo#123456: This is the summary to the describe the bug in a short form : OPEN`
@marcus-h: Please review
=> show issues (bugs) in interactive review diff

osc/util/debquery.py
Similar to recent fixes in libsolv and obs-build. Since tarfile
on python2 doesn't do lzma, decompress the file into memory and
feed it as a fake file via StringIO to tarfile
=> debquery: support control.tar.xz

osc/commandline.py
This is needed for running expect, for example.
=> osc chroot: also mount devpts

osc/commandline.py
was: 
`Creating binaries`
is now:
`Creating directory "binaries"`
=> change output when creating binaries directory

osc/core.py
catch IncompleteRead() and retry until retry_counter is reached. Then re-raise IncompleteRead().
fixes #402 
@marcus-h: please review (tested with python2 and python3)
=> fixed IncompleteRead(0) error on long builds.

osc/commandline.py, osc/conf.py
Required for https://github.com/openSUSE/obs-build/pull/214
=> Export a real name for vc to consume

osc/OscConfigParser.py
=> Fix Python 3.7 support

osc/OscConfigParser.py
See PEP 479
raise StopIteration() is not needed.
=> [python3] Fix Python 3.7 support

osc/commandline.py, osc/core.py, tests/results_fixtures/oscrc, tests/results_fixtures/result-dirty.xml, tests/results_fixtures/result.xml, tests/suite.py, tests/test_results.py
Like: osc results --watch
Test osc results and prjresults
=>  Add --watch for osc prjresults --xml 

osc/oscerr.py
=> [python3] self[i] is now self.args[i]

osc/cmdln.py
enable full python3 support for man page building
=> [python3] enable full python3 support for man page building

osc/util/rpmquery.py
* new function cmp (not available in python3)
* decode unpack data
=> [python3] rpmquery.py now python3 ready

setup.py
=> [python3] setup.py now supports python3

osc/babysitter.py
needs https://github.com/openSUSE/osc/pull/464 to work
=> [python3] babysitter.py msg and body are byte strings

osc/oscssl.py
* works also with python2
Should be safe to merge immediately.
=> [python3] make oscssl.py python3 ready.

osc/build.py
* return of get_buildinfo is bytestring with python3
* other variables contain bytestrings as well now
needs https://github.com/openSUSE/osc/pull/464 to work
=> [python3] build.py with python3 (mostly bytestring)

osc/core.py
* use cmp_to_key from functools for python 2.7 and higer
* use self written cmp_to_key for python 2.6
* new functions compare und cmp (used in python2 and python3)
* a lot of bytestring handling and decoding
needs https://github.com/openSUSE/osc/pull/464 to work
Merge only together with https://github.com/openSUSE/osc/pull/493
=> [python3] python3 support for core library

osc/commandline.py
* use cmp_to_key from functools for python 2.7 and higer
* use self written cmp_to_key for python 2.6
* a lot of bytestring handling and decoding
needs https://github.com/openSUSE/osc/pull/464 to work.
Merge only together with https://github.com/openSUSE/osc/pull/492
=> [python3] python3 support for commandline module

osc/fetch.py
* the result of a division is a float
but we need int to continue.
=> [python3] fetch.py python3 ready

osc/util/packagequery.py
name, arch, version and release need to be decoded
=> [python3] fix decoding for packageqeury.py

osc/commandline.py
The offline mode does not really work offline since
parse_repoarchdescr() uses get_buildconfig to store the
buildconfig in a temporary file.
Solution:
Use the same logic as in build.py. If in offline mode(noinit = True)
try to use the local _buildconfig file. If not in offline mode just
download the buildconfig from the server via get_buildconfig
fixes https://github.com/openSUSE/osc/issues/560
=> fix offline build mode

NEWS, osc/commandline.py, osc/core.py
via --enforce-branching option
This may be default by server side settings
=> allow implicit branch on maintenance request creation

osc/core.py, tests/test_update.py
typo leaded to wrong parameter
=> fix checkout of meta files

NEWS, osc/commandline.py, osc/core.py
no single option since it is really a special usecase IMHO
jsc#OBS-40
=> add --lastsucceeded option for logfile display

osc/fetch.py
=> remove decoding of hdr.filename

osc/build.py, osc/commandline.py
This fixes some regressions with osc chroot:
- osc chroot --wipe --root=/dir/ can now be called outside
a working copy
- osc chroot --noinit --root=/dir/ can now be called outside
a working copy and behaves like the old code (Just entering
the chroot without any modifications)
- The confirmation of the deletion is implemented again and thus
the --force option was implemented too.
This needs all to be done before self.parse_repoarchdescr() call. If no opts.noinit is set the opts.shell is set to true and the buildroot gets initialized before entering the shell.
fixes https://github.com/openSUSE/osc/issues/709, https://github.com/openSUSE/osc/issues/706 and https://github.com/openSUSE/osc/issues/711
=> fix regression in osc chroot

osc/build.py
=> e.reason is a string not a integer decimal

.travis.yml, MANIFEST.in, setup.py
* Reformatted `.travis.yml`
* Reformatted `setup.py`
* Used `before_*` statements instead of script chains
* Changed `setup.py` to build a proper Python package for PyPI
* fixes #658
* fixes #708
=> Fixed problems in automated deployment via Travis CI

docs/api/modules.rst, docs/api/osc.OscConfigParser.rst, docs/api/osc.build.rst, docs/api/osc.conf.rst, docs/api/osc.core.rst, docs/api/osc.credentials.rst, docs/api/osc.util.rst, docs/index.rst
removed tutorial. Added missing osc.util.helper
added more modules:
* OscConfigParser
* build
* conf
* credentials
=> improve documenation

osc/build.py, osc/commandline.py
I need this to automate build script tests ...
=> complete --shell-cmd support

osc/commandline.py, osc/core.py
Show the state of the issues (added, deleted, changed)
of the issues in a list.
Also --xml can now be given to get the raw xml output from the server.
fixes https://github.com/openSUSE/osc/issues/798
=> Add more infos to issues rdiff

osc/commandline.py
help rdiff: -p shows diff of files in archives
This was undocumented.
=> help rdiff: -p shows diff of files in archives

osc/babysitter.py, osc/commandline.py
Fixes #584
@lethliel What’s wrong with something as simple as this?
=> Ignore signal.SIGWINCH.

osc/commandline.py
yes, ugly, but I am tired to explain people to add a .git suffix
to get the right mode for "osc add"
=> catch URLs to github.com and gitlab.com as git repos

osc/commandline.py
for use in Arch, Debian and Ubuntu
Fixes https://github.com/openSUSE/osc/issues/201
=> add proper reporuls

osc/core.py
Some services expect "old" service files (that is, files from a
previous service run) to be present in an ".old" dir. Hence, osc
should support that.
Instead of removing all files from a previous service run, move them
to the ".old" dir, run the services, and, finally, remove the ".old"
dir.
Unfortunately, the location of the ".old" dir is hardcoded in the
specific services. That is, we have to be careful if an ".old" dir
exists (in this case, we error out).
Based on [1].
[1] https://github.com/openSUSE/osc/pull/846
=> Add .old dir support for source services

NEWS, osc/commandline.py
thought we have it since > 10 years ....
=> add showlinked command

NEWS, osc/build.py, osc/commandline.py
(minor code improvement for handing over release number)
=> add new stage option for the build script

osc/conf.py, osc/core.py
```
The old code only supports a file whose size is less then or equal
to INT_MAX (due to a reasonable(!) limit in M2Crypto). The actual
issue is in core.http_request which mmap(...)s the file, wraps it
into a memoryview/buffer and then passes the memoryview/buffer to
urlopen. Eventually, the whole memoryview/buffer is read into memory
(see m2_PyObject_GetBufferInt). If the file is too large (> INT_MAX),
m2_PyObject_GetBufferInt raises a ValueError (which is perfectly
fine!).
Reading a whole file into memory is completely insane. In order to
avoid this, we now simply pass a file-like object to urlopen (more
precisely, the file-like object is associated with the Request
instance that is passed to urlopen). The advantange is that the
file-like object is processed in chunks of 8192 bytes …
```
=> Support an arbitrary sized file in core.http_request

osc/build.py
it can not work and build script will direct complain in future
=> do not use preinstallimages when building as non-root

NEWS, osc/build.py
We need to hand over the sysroot rpms in rpmlist with a prefix. And we
need to take care of the "crossarch" definition in buildinfo
=> support cross compile using a sysroot

osc/core.py
Offer a force ("f") choice if, for instance, "osc meta prj foobar -e"
fails due to a HTTPError in metafile.edit. If the force choice is
selected, a new url is constructed by invoking the metafile._URLBuilder
instance with a "force='1'" argument (this adds a "force=1" to the
original url's query string (*)) and the corresponding file is PUTed
to the new url. If this PUT fails again and now the "y" choice is
selected, the file is PUTed to the original url (*).
(*): Stricly speaking, from metafile.edit's POV, the concrete url
depends on the passed in metafile._URLBuilder instance, though.
Note: the metafile._URLBuilder class and its is_force_supported method
is a gross hack. That's why this class is marked as private (that is,
we can remove it at any point in time again without breaking the …
=> Offer a force ("f") choice in metafile.edit's error handling code path

osc/commandline.py
- Use makeurl instead of manual URL construction in do_token
- Add support for creating a workflow token via "osc token"
(for the details, see the individual commits)
=> Small do_token cleanup + support creation of a workflow token

osc/commandline.py, osc/core.py
not 100% sure if the self.baserev check may lead to problems elsewhere ...
=> detachbranch: remove _link when link target got removed

osc/build.py, osc/fetch.py
Some of our repositories have specific download urls. osc is ignoring
this so far and just tries to use the generic downloadurl
This code prefers definitions for individual path elements if they exist.
We could IMHO remove the old code, since old OBS instances would still
work via the api download fallback.
Real life examples for repo specific configs are on openSUSE all
repositories outside of the /repositories/ directory. eg.
<path project="openSUSE:Tumbleweed" repository="dod" url="http://download.opensuse.org/tumbleweed/repo/oss/"/>
=> fix downloading from mirrors

tests/common.py
=> OscTestCase: Always reset CWD

osc/build.py
Fixes https://github.com/openSUSE/osc/issues/322
=> build: Fix printing paths to built debian packages

NEWS, osc/build.py, osc/commandline.py
shows kernel messages (only) atm
=> add build --verbose option for build script

osc/commandline.py
=> Add -F option to osc submitreq

osc/core.py
Based on a suggesstion of
Co-Author: Jan Zerebecki <jzerebecki@suse.com>
Please do not merge it directly, but let's discuss about the text here first.
=> Trying to improve maintenance warning

osc/credentials.py
Consider this more a bugreport then a pull request, but osc is bascially unusable here due to exceptions.
=> dealing with new exception errors

osc/core.py
=> Revert "Quote unicode characters in URL path"

osc/core.py
This table formatting code calculates the widest column before printing. It can be generalized for other tabular data if needed.
```python
distribution              project                   repository                reponame
------------              -------                   ----------                --------
openSUSE Tumbleweed       openSUSE:Factory          snapshot                  openSUSE_Tumbleweed
openSUSE Leap 15.2        openSUSE:Leap:15.2        standard                  openSUSE_Leap_15.2
openSUSE Leap 15.2 ARM    openSUSE:Leap:15.2:ARM    ports                     openSUSE_Leap_15.2_ARM
openSUSE Leap 15.2 PowerPC openSUSE:Leap:15.2:PowerPC ports                     openSUSE_Leap_15.2_PowerPC
openSUSE Leap 15.1        openSUSE:Leap:15.1        standard …
```
=> Pretty print `osc dists` output

osc/build.py, osc/commandline.py
waits for https://github.com/openSUSE/osc/pull/998 to be merged / reviewed first.
=> Add osc helm build type support

osc/cmdln.py, osc/commandline.py
=> Never require login in the help command

dist/osc.complete
=> Add missing space to copypac completion

NEWS, osc/commandline.py, osc/conf.py, osc/core.py
* init command is working inside of a git repository
* downloadassets command fetches references assets from build description
* checkout is cloning from git
=> initial obs-git support

osc/commandline.py
=> add another exception for github URLs for "osc add"

osc/build.py, osc/conf.py, osc/core.py, osc/util/packagequery.py
this helps with building for example in devel:languages:c_c++
=> Fix quoting of download urls

osc/conf.py
The file names from ssh(1) man page.
=> Update list of considered file names for ssh key autodetection

osc/commandline.py, osc/core.py, osc/oscerr.py, tests/test_core.py
=> parseRevisionOption(): Raise an exception on invalid revisons

osc/core.py
=> Add missing attributes to Package when scm_url is set

osc/credentials.py
=> Fix crash when 'pass' is not set in the config file

osc/commandline.py, osc/core.py
=> Fix -M/--multibuild user experience, allow globs where possible

osc/commandline.py
=> Do not ask for login for `-h,--help`

osc/commandline.py
Debug prints are needed for troubleshooting ARCH selection problem in
https://github.com/openSUSE/osc/pull/241#issuecomment-1203463612
=> Reworded `build` help and added debug prints

osc/commandline.py
osc version output:
```
osc version
1.0.0b1+15.git.f86fb665
```
=> add version command to print the used version

osc/conf.py, tests/test_conf.py
Fixes problems in reading conf values before the configuration
is fully initialized.
=> Convert defaults to their expected types

osc/util/git_version.py
=> git_version: Return version from the source code if there's no matching tag

osc/commandline.py
=> Do not list declined requests by default

osc/commandline.py
=> Replace imp with importlib

osc/core.py
=> Fix 'osc up' on project level for scm packages

osc/connection.py
This usually happens when a user runs multiple osc instances
from the command-line in parallel.
=> Lock cookiejar to prevent unnecessary signature auth

osc/commandline.py, osc/core.py, tests/prdiff_fixtures/request, tests/test_commit.py, tests/test_core_request.py, tests/test_prdiff.py, tests/test_request.py
=> Properly handle osc rq -M/--mine option

NEWS, osc/cmdln.py, osc/commandline.py, osc/core.py, osc/oscerr.py
which allows to create a working config for pbuild tool based on OBS server side data
The cross build support is not yet done
=> add create-pbuild-config(cpc) command

osc/commandline.py
we have a mix of os.curdir and os.getcwd(). consolidate on the python 3.x recommended method of Path.cwd()
=> use Path.cwd() consistently

osc/commandline.py
=> rq list --all: Avoid conflict with the --state option

osc/build.py
in build we imported "conf" and "from .conf import config" which let to two different instances of config: "global config" at import was the DEFAULTS array, and conf.config the updated config after reading the user configuration.
Convert everything to use conf.config as everywhere else, which makes setting of build defaults in the oscrc work again (like build-jobs).
=> avoid importing the config global variable

osc/commandline.py, osc/core.py
=> Add --disable-build option to linkpac and branch commands

osc/core.py
=> Handle empty EDITOR=/PAGER= env variable properly

osc/connection.py, osc/core.py
This is a bulk add of typing that also includes the formatting with darker.
=> mypy: Add types to methods

osc/_private/__init__.py, osc/_private/api.py, osc/_private/api_build.py, osc/_private/package.py, osc/_private/request.py, osc/commandline.py, osc/core.py, tests/test_commandline.py
=> Fix buildhistory cli and output

osc/core.py, tests/test_setlinkrev.py
=> setlinkrev: Write a log message on setting a revision

behave/features/linkpac.feature, osc/commandline.py, osc/core.py, tests/test_commandline.py
=> linkpac: Fix linking a locked package, improve CLI code

behave/features/rdelete.feature, osc/core.py
=> use correct variable prj instead of project

behave/features/rm.feature
=> behave: Test rm on multiple files

behave/features/copypac.feature, osc/commandline.py, osc/core.py
=> copypac: Fix downgrading a package to an old revision

osc/connection.py
=> connection: Mute the "Converted retries value" debug message

behave/features/buildhist.feature, osc/_private/api_build.py, osc/commandline.py
=> buildhist: Fix running from a package checkout

behave/features/rdiff.feature, osc/commandline.py
=> rdiff: Fix traceback when new project is not specified

osc/commandline.py, osc/core.py
=> rq list: Fix passing values of the --type option

README.md
Preview [available here](https://github.com/openSUSE/osc/blob/df1f881a72d99ea6d4693c6231ba70337401e7f7/README.md)
=> README: repair unit tests + code quality badges

osc/commandline.py, osc/core.py
Modify it to use pathlib.Path along with its callers. Some str(path) was necessary to avoid having a large changeset.
It addresses #1258 and continues the work started in bac162a7123524fb3521e52c90d05f6577b7c25e.
=> checkout_package: Use pathlib.Path

behave/container-run.sh, behave/container-setup-prebuilt-rpms.sh, behave/container-setup.sh, behave/fixtures/prj/test_factory.xml, osc/build.py, osc/conf.py, osc/fetch.py, tests/test_conf.py
=> build: New option 'disable_hdrmd5_check' to ignore hdrmd5 mismatches

osc/commandline.py, osc/conf.py
=> Fix interactive config setup

osc/commandline.py
I discovered that this command no longer worked, but I needed it, so I fixed it.
=> Fix creq command not working

osc/core.py
=> Document 'popt' attribute in the _link template

osc/commandline.py
=> Identify inherited packages in the 'dependson' command output

osc/babysitter.py
=> Fix a traceback when failed to unlock a keyring

osc/build.py, tests/test_build.py
=> Add glob support to the 'trusted_prj' config option

osc/core.py
=> Fix core.xmlindent() to work with ElementTree objects

osc/commandline.py
=> Fix 'diff' command when no files are specified

behave/features/steps/osc.py, behave/features/user.feature, behave/fixtures/user/unicode.xml, osc/connection.py, osc/credentials.py
=> Correctly handle passwords with utf-8 characters

osc/commandline.py, osc/core.py
=> Add highlighting for "osc diff" and similar commands

behave/features/repo.feature, osc/_private/api.py, osc/_private/project.py, osc/commands/repo.py, osc/commands/repo_add.py, osc/commands/repo_list.py, osc/commands/repo_remove.py, osc/output/__init__.py, osc/output/key_value_table.py, osc/output/tty.py, osc/output/widechar.py, setup.cfg, tests/test_output.py
=> Add 'repo' command and subcommands for managing repositories in project meta

osc/build.py
=> Fix string + int concatenation errors in 'build' command by using f-strings

AUTHORS
I switched my last name - following up just here.
=> Update AUTHORS: change my last name

osc/conf.py, osc/store.py, tests/test_git_scm_store.py, tests/test_store.py
=> Fix handling empty vm_type in Store.last_buildroot

osc/commandline.py, osc/core.py
=> add support for keep_packages_locked on request revoke

osc/conf.py
=> Fix retrieving a password in case a function returns another callable

behave/features/createrequest.feature, behave/features/steps/common.py, behave/features/submitrequest.feature
=>  Add behave tests for 'createrequest -a submit --supersede' and 'submitrequest --supersede'

osc/commandline.py
In some cases the exit code is all you want
=> Allow -X HEAD on osc api requests as well

osc/commandline.py, osc/conf.py, osc/meter.py, osc/util/models.py, tests/test_conf.py, tests/test_models.py
=> Don't show progressbars when --quiet is specified

osc/babysitter.py, osc/core.py
Fixes: #1478
Related: https://github.com/openSUSE/open-build-service/issues/15605
=> Error out when branching a scmsync package

osc/conf.py, osc/core.py, osc/oscssl.py
=> Honor XDG_CONFIG_HOME and XDG_CACHE_HOME env vars

osc/build.py, osc/commandline.py
=> Fix 'buildinfo' command

osc/_private/api_source.py, osc/_private/common.py, osc/babysitter.py, osc/commandline.py, osc/connection.py, osc/core.py, osc/obs_api/__init__.py, osc/obs_api/enums.py, osc/obs_api/person.py, osc/obs_api/person_owner.py, osc/obs_api/person_watchlist.py, osc/obs_api/person_watchlist_package.py, osc/obs_api/person_watchlist_project.py, osc/obs_api/person_watchlist_request.py, osc/output/__init__.py, osc/output/output.py, osc/util/models.py, tests/test_output.py
=> Introduce obs_api.Person, migrate some code to it

osc/credentials.py
=> Cache password from SecretService to avoid spamming user with an accept dialog

osc/commandline.py
=> Never ask for credentials when displaying help

osc/core.py
=> Fix linkpac

osc/cmdln.py, osc/commandline.py
=> Document '--buildtool-opt=--noclean' example in 'build' command's help

osc/obs_scm/serviceinfo.py
=> Improve 'service' command by printing names of running services

osc/build.py, osc/conf.py
=> Change 'build' command to pass '--jobs' option to 'build' tool only if 'build_jobs' > 0

behave/features/linkpac.feature, osc/core.py
=> Fix 'linkpac' command crash when used with '--disable-build' or '--disable-publish' option

osc/commandline.py
=> Fix typos in commandline.py

osc/meter.py
=> Implement meter.SimpleTextMeter that prints what's being downloaded

osc/build.py, osc/commandline.py
The suffix can be
packageid
flavor
packageid-reponame
flavor-reponame
Also adding support already for "Containerfile", support will come to OBS as well (same file, just different name)
=> Support Dockerfile.* in _multibuild packages

osc/commandline.py
and make repository definitions optional.
=> creq: Allow to specify source and target repository

osc/commandline.py, osc/obs_api/token.py
Add missing parameters for token triggers. Esp used for rebuild and release commands.
=> Support parameters on token triggers

.github/workflows/linters.yaml, .github/workflows/tests.yaml, behave/README.md, osc/obs_scm/store.py, tests/test_store.py
=> Fix store migration from 1.0 to 2.0 when there is a 'sources' file that would conflict with 'sources' directory

osc/obs_scm/package.py
=> Change 'update' command to treat empty '.osc/_in_update/_files' as missing

osc/core.py, osc/obs_api/request_action_source.py
It is a private patch/extension now, to be upstreamed soon.
=> Extend RequestActionSource with 'repository' attribute

osc/commandline.py, osc/commandline_common.py, osc/commands/repo_add.py, osc/commands/repo_list.py, osc/commands/repo_remove.py
=> Speed improvements

osc/commandline.py
=> Document that 'status' command prints unmodified files in verbose output

osc/connection.py
=> Save session cookie even if a request fails

osc/conf.py
=> Mute oscrc permissions warning when there's no password set

osc/_private/api.py, osc/build.py, osc/commandline.py, osc/core.py, osc/obs_api/package.py, osc/obs_api/person.py, osc/obs_api/token.py, osc/obs_scm/package.py, osc/obs_scm/project.py, osc/obs_scm/serviceinfo.py, osc/obs_scm/store.py, osc/util/models.py, osc/util/repodata.py, osc/util/xml.py, tests/common.py, tests/test_request.py
=> Extend xml.etree.ElementTree.ParseError output with a snippet of broken XML

behave/features/linkpac.feature, osc/core.py
=> Fix 'linkpac' command for projects with a project link

osc/commandline.py, osc/core.py
=> Fix 'osc checkout' command to support deleted packages incl. revisions

osc/core.py
=> Don't highlight unchanged empty lines as trailing whitespace lines

osc/commandline.py, osc/core.py
=>  Change 'osc whatdependson' command to take multiple '-M' options incl. wildcards

osc/commandline.py
Followup for c4c2d2a9330239139ae2e609885a9df574e83cfd
=> Add missing project_separator substitutions

osc/connection.py
=> Change a debug message to a warning if ssh-keygen is not available

.github/workflows/tests.yaml, behave/features/environment.py, behave/features/git-osc-precommit-hook.feature, behave/features/steps/osc.py, behave/features/steps/podman.py, git-osc-precommit-hook.py, osc/babysitter.py, osc/commandline.py, setup.cfg
and create a binary to call it directly
=> Add osc service precommit, for use with git hook

osc/gitea_api/connection.py
Related upstream issue: https://github.com/urllib3/urllib3/issues/3595
=> Fix git-obs connection for urllib3 v1 by overriding the default timeout

osc/gitea_api/__init__.py, osc/gitea_api/branch.py, osc/gitea_api/connection.py, osc/gitea_api/exceptions.py, osc/gitea_api/fork.py
Fixes the second traceback in: #1781
=> Improve handling exceptions in 'git-obs' command

osc/commands_git/pr_create.py, tests/test_git_editor.py
=> Fix git-obs pr create with multistring EDITOR

osc/gitea_api/exceptions.py
=> Improve message in 301: Moved Permanently error in git-obs

osc/git_scm/store.py, tests/test_git_scm_store.py
=> Fix git store when .git is a file with "gitdir: <path>" link

osc/connection.py
=> Do not use pipe for ssh-keygen input

osc/git_scm/store.py
=> Return None if GitStore cannot determine apiurl

osc/gitea_api/pr.py
=> Allow pull request IDs in <owner>/<repo>!<number> format

osc/core.py
=> Tolarate empty flavor in multibuild resolve

osc/commandline_git.py, osc/gitea_api/conf.py
=> Change 'git-obs -G' to accept url to select a gitea login entry

osc/commands_git/pr_review_interactive.py, osc/gitea_api/git.py, osc/gitea_api/tardiff.py
=> Fix various crashes in 'git-obs pr review interactive'
